bundles:
    # Set a priority higher than the priority of the ShippingBundle (i.e. 200) to ensure that all dependencies
    # from the ShippingBundle are loaded before the dependent methods of your bundle.
    - { name: Acme\Bundle\FastShippingBundle\AcmeFastShippingBundle, priority: 200 }
