services:
    _defaults:
        public: true

    AcmeDemoBundleRestApiController:
        namespace: Acme\Bundle\DemoBundle\Controller\Api\Rest\
        resource: '../../Controller/Api/Rest/*Controller.php'
        calls:
            - [setContainer, ['@service_container']]
