services:

    Acme\Bundle\DemoBundle\Entity\Repository\PriorityRepository:
        parent: oro_entity.abstract_repository
        tags:
            - { name: doctrine.repository_service }

    Acme\Bundle\DemoBundle\Entity\Repository\DocumentRepository:
        parent: oro_entity.abstract_repository
        tags:
            - { name: doctrine.repository_service }

    Acme\Bundle\DemoBundle\Entity\Repository\QuestionRepository:
        parent: oro_entity.abstract_repository
        tags:
            - { name: doctrine.repository_service }

    Acme\Bundle\DemoBundle\Entity\Repository\FavoriteRepository:
        parent: oro_entity.abstract_repository
        tags:
            - { name: doctrine.repository_service }

    Acme\Bundle\DemoBundle\Entity\Repository\SmsRepository:
        parent: oro_entity.abstract_repository
        tags:
            - { name: doctrine.repository_service }

    Acme\Bundle\DemoBundle\Entity\Repository\DoctrineTypeFieldRepository:
        parent: oro_entity.abstract_repository
        tags:
            - { name: doctrine.repository_service }
