services:
    _defaults:
        public: true

    Acme\Bundle\CMSBundle\Controller\BlockController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
