services:
    acme.cms.form.type.block:
        class: Acme\Bundle\CMSBundle\Form\Type\BlockType
        tags:
            - { name: form.type, alias: acme_cms_block }

    acme.cms.validator_constraints.unique_title_draft_field_validator:
        class: Acme\Bundle\CMSBundle\Validator\Constraints\UniqueTitleDraftValidator
        arguments:
            - '@doctrine'
            - '@oro_draft.manager.draftable_filter'
        tags:
            - { name: validator.constraint_validator }
