Acme\Bundle\CMSBundle\Entity\Block:
    properties:
        title:
            - Acme\Bundle\CMSBundle\Validator\Constraints\UniqueTitleDraft: ~
            - NotBlank: ~
            - Length:
                  max: 255
