services:
    _defaults:
        public: true

    ACME\Bundle\WysiwygBundle\Controller\BlogPostCrudController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
