oro_search:
    engine_dsn: "orm:"
    engine_parameters:
        force_refresh: true
        language_optimization: true
        relevance_optimization: true
        log_queries: false
        #    item_container_template: '@My/Search/itemContainer.html.twig'
        required_attributes: [ ]
        required_plugins: [ ]
        index:
            prefix: 'oro_search'
            body:
                settings:
                    analysis:
                        char_filter:
                            cleanup_characters:
                                type: 'mapping'
                                mappings:
                                    - "- => "
                                    - "— => "
                                    - "_ => "
                                    - ". => "
                                    - "/ => "
                                    - "\\\\ => "
                                    - ": => "
                                    - "! => "
                                    - "' => "
                                    - "` => "
                                    - "\" => "
                        analyzer:
                            fulltext_search_analyzer:
                                filter:
                                    - "wordsplit"
                                    - "lowercase"
                                    - "unique"
                                char_filter:
                                    - "cleanup_characters"
                                tokenizer: "whitespace"
                            fulltext_index_analyzer:
                                filter:
                                    - "wordsplit"
                                    - "lowercase"
                                    - "substring"
                                    - "unique"
                                char_filter:
                                    - "html_strip"
                                    - "cleanup_characters"
                                tokenizer: "whitespace"

oro_website_search:
    engine_parameters:
        language_optimization: true
        remove_unused_fulltext: true
        relevance_optimization: true
        index:
            prefix: 'oro_website_search'
            body:
                settings:
                    analysis:
                        char_filter:
                            cleanup_characters:
                                type: 'mapping'
                                mappings:
                                    - "- => "
                                    - "— => "
                                    - "_ => "
                                    - ". => "
                                    - "/ => "
                                    - "\\\\ => "
                                    - ": => "
                                    - "! => "
                                    - "' => "
                                    - "` => "
                                    - "\" => "
                        analyzer:
                            fulltext_search_analyzer:
                                filter:
                                    - "wordsplit"
                                    - "lowercase"
                                    - "unique"
                                char_filter:
                                    - "cleanup_characters"
                                tokenizer: "whitespace"
                            fulltext_index_analyzer:
                                filter:
                                    - "wordsplit"
                                    - "lowercase"
                                    - "substring"
                                    - "unique"
                                char_filter:
                                    - "html_strip"
                                    - "cleanup_characters"
                                tokenizer: "whitespace"

oro_organization_pro:
    ignore_preferred_organization_tokens:
        - cme\Bundle\DemoBundle\Security\AcmeWsseToken
