navigation:
    menu_config:
        items:
            blog_post_list:
                label: 'acme.wysiwyg.blogpost.entity_plural_label'
                route: 'acme_wysiwyg_blog_post_index'
                extras:
                    routes: [ '/^acme_wysiwyg_blog_post_/' ]

        tree:
            application_menu:
                children:
                    system_tab:
                        children:
                            entities_list:
                                children:
                                    blog_post_list: ~

    titles:
        acme_wysiwyg_blog_post_index: ~
        acme_wysiwyg_blog_post_view: '%entity.id%'
        acme_wysiwyg_blog_post_create: 'oro.ui.create_entity'
        acme_wysiwyg_blog_post_update: '%entity.id% - oro.ui.edit'
